server:
  servlet:
    context-path: /reodeling
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/remodeing
    username: root
    password: 123123
