-- 创建数据库remodeling
DROP DATABASE IF EXISTS `remodeling`;
CREATE DATABASE `remodeling` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- 创建数据表：users
DROP TABLE IF EXISTS users;
CREATE TABLE users
(
    id            BIGINT UNSIGNED AUTO_INCREMENT COMMENT '主键' PRIMARY KEY,
    username      VARCHAR(32) DEFAULT NULL COMMENT '用户名',
    password      VARCHAR(32) DEFAULT NULL COMMENT '密码',
    register_time DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '注册时间',
    create_time   DATETIME    DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间',
    update_time   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE = InnoDB
  AUTO_INCREMENT = 1
  DEFAULT CHARSET = utf8mb4 COMMENT '用户表';